export const REDUCER_CASES ={
    SET_TOKEN : "SET_TOKEN",
    SET_PLAYLISTS : "SET_PLAYLISTS",
    SET_PLAYLIST_ID : "SET_PLAYLIST_ID",
    SET_PLAYLIST : " SET_PLAYLIST",
    SET_PLAYING: "SET_PLAYING",
    SET_PLAYING_STATE: "SET_PLAYING_STATE"
}